//
//  AddArrayModels.swift
//  Shopping_Mall
//
//  Created by Norayr Grigoryan on 6/29/21.
//

/*
 "id": 0, //ignor
 "userID": 0,
 "subCategoryID": 0,
 "currency": 0,
 "price": 0,
 "salePercent": 0, //ignor
 "salePrice": 0, //ignor
 "country": 0,
 "region": 0,
 "city": 0,
 "state": 0,
 "description": "string",
 "name": "string", //auto generated and editable
 "locationLatitude": 0,
 "locationLongitude": 0,
 "contact": "string",
 "aim": 0,
 "owner": 0,
 "comment": "string", //ignor
 "view": 0, //ignor
 "tags": "string",
 "imagesList": ["string"],
 "space": 0,
 "constructionType": 0,
 "paymentTime": 0,
 "rooms": 0,
 "floor": 0
 
 */

import Foundation
import UIKit

final class AddArrayModels: NSObject {
    
    static var realEstate = ["id": 0,
                             "userID": 0,
                             "subCategoryID": 0,
                             "currency": 0,
                             "price": 0,
                             "salePercent": 0,
                             "salePrice": 0,
                             "countryName": "string",
                             "regionName": "string",
                             "cityName": "string",
                             "country": 0,
                             "region": 0,
                             "city": 0,
                             "state": 0,
                             "description": "string",
                             "name": "string",
                             "locationLatitude": 0,
                             "locationLongitude": 0,
                             "contact": "string",
                             "aim": 0,
                             "owner": 0,
                             "comment": "string",
                             "view": 0,
                             "tags": "string",
                             "isRegional": true,
                             "imagesList": ["string"],
                             "space": 0,
                             "constructionType": 0,
                             "paymentTime": 0,
                             "rooms": 0,
                             "floor": 0] as [String : Any]
    
    
    static var appliance = ["id": 0,
                            "userID": 0,
                            "subCategoryID": 0,
                            "currency": 0,
                            "price": 0,
                            "salePercent": 0,
                            "salePrice": 0,
                            "countryName": "string",
                            "regionName": "string",
                            "cityName": "string",
                            "country": 0,
                            "region": 0,
                            "city": 0,
                            "state": 0,
                            "description": "string",
                            "name": "string",
                            "locationLatitude": 0,
                            "locationLongitude": 0,
                            "contact": "string",
                            "aim": 0,
                            "owner": 0,
                            "comment": "string",
                            "view": 0,
                            "tags": "string",
                            "isRegional": true,
                            "imagesList": ["string"],
                            "productState": 0] as [String : Any]
    
    static var householdGoods = ["id": 0,
                                 "userID": 0,
                                 "subCategoryID": 0,
                                 "currency": 0,
                                 "price": 0,
                                 "salePercent": 0,
                                 "salePrice": 0,
                                 "countryName": "string",
                                 "regionName": "string",
                                 "cityName": "string",
                                 "country": 0,
                                 "region": 0,
                                 "city": 0,
                                 "state": 0,
                                 "description": "string",
                                 "name": "string",
                                 "locationLatitude": 0,
                                 "locationLongitude": 0,
                                 "contact": "string",
                                 "aim": 0,
                                 "owner": 0,
                                 "comment": "string",
                                 "view": 0,
                                 "tags": "string",
                                 "isRegional": true,
                                 "imagesList": ["string"],
                                 "productState": 0] as [String : Any]
    
    static var clothesAndShoes = ["id": 0,
                                  "userID": 0,
                                  "subCategoryID": 0,
                                  "currency": 0,
                                  "price": 0,
                                  "salePercent": 0,
                                  "salePrice": 0,
                                  "countryName": "string",
                                  "regionName": "string",
                                  "cityName": "string",
                                  "country": 0,
                                  "region": 0,
                                  "city": 0,
                                  "state": 0,
                                  "description": "string",
                                  "name": "string",
                                  "locationLatitude": 0,
                                  "locationLongitude": 0,
                                  "contact": "string",
                                  "aim": 0,
                                  "owner": 0,
                                  "comment": "string",
                                  "view": 0,
                                  "tags": "string",
                                  "isRegional": true,
                                  "imagesList": ["string"],
                                  "productState": 0,
                                  "clothingSize": "string",
                                  "shoesSize": 0] as [String : Any]
    
    static var forChildren = ["id": 0,
                              "userID": 0,
                              "subCategoryID": 0,
                              "currency": 0,
                              "price": 0,
                              "salePercent": 0,
                              "salePrice": 0,
                              "countryName": "string",
                              "regionName": "string",
                              "cityName": "string",
                              "country": 0,
                              "region": 0,
                              "city": 0,
                              "state": 0,
                              "description": "string",
                              "name": "string",
                              "locationLatitude": 0,
                              "locationLongitude": 0,
                              "contact": "string",
                              "aim": 0,
                              "owner": 0,
                              "comment": "string",
                              "view": 0,
                              "tags": "string",
                              "isRegional": true,
                              "imagesList": ["string"],
                              "productState": 0,
                              "gender": true,
                              "forNewBorns": true] as [String : Any]
    
    static var jewerlyAndAccessories = ["id": 0,
                                        "userID": 0,
                                        "subCategoryID": 0,
                                        "currency": 0,
                                        "price": 0,
                                        "salePercent": 0,
                                        "salePrice": 0,
                                        "countryName": "string",
                                        "regionName": "string",
                                        "cityName": "string",
                                        "country": 0,
                                        "region": 0,
                                        "city": 0,
                                        "state": 0,
                                        "description": "string",
                                        "name": "string",
                                        "locationLatitude": 0,
                                        "locationLongitude": 0,
                                        "contact": "string",
                                        "aim": 0,
                                        "owner": 0,
                                        "comment": "string",
                                        "view": 0,
                                        "tags": "string",
                                        "isRegional": true,
                                        "imagesList": ["string"],
                                        "productState": 0,
                                        "gender": true] as [String : Any]
    
    static var construction = ["id": 0,
                               "userID": 0,
                               "subCategoryID": 0,
                               "currency": 0,
                               "price": 0,
                               "salePercent": 0,
                               "salePrice": 0,
                               "countryName": "string",
                               "regionName": "string",
                               "cityName": "string",
                               "country": 0,
                               "region": 0,
                               "city": 0,
                               "state": 0,
                               "description": "string",
                               "name": "string",
                               "locationLatitude": 0,
                               "locationLongitude": 0,
                               "contact": "string",
                               "aim": 0,
                               "owner": 0,
                               "comment": "string",
                               "view": 0,
                               "tags": "string",
                               "imagesList": ["string"],
                               "productState": 0] as [String : Any]
    
    static var allForHomeAndGarden = ["id": 0,
                                      "userID": 0,
                                      "subCategoryID": 0,
                                      "currency": 0,
                                      "price": 0,
                                      "salePercent": 0,
                                      "salePrice": 0,
                                      "countryName": "string",
                                      "regionName": "string",
                                      "cityName": "string",
                                      "country": 0,
                                      "region": 0,
                                      "city": 0,
                                      "state": 0,
                                      "description": "string",
                                      "name": "string",
                                      "locationLatitude": 0,
                                      "locationLongitude": 0,
                                      "contact": "string",
                                      "aim": 0,
                                      "owner": 0,
                                      "comment": "string",
                                      "view": 0,
                                      "tags": "string",
                                      "isRegional": true,
                                      "imagesList": ["string"],
                                      "productState": 0] as [String : Any]
    static var sport = ["id": 0,
                        "userID": 0,
                        "subCategoryID": 0,
                        "currency": 0,
                        "price": 0,
                        "country": 0,
                        "region": 0,
                        "city": 0,
                        "state": 0,
                        "description": "string",
                        "name": "string",
                        "locationLatitude": 0,
                        "locationLongitude": 0,
                        "contact": "string",
                        "aim": 0,
                        "owner": 0,
                        "tags": "string",
                        "isRegional": true,
                        "imagesList": ["string"],
                        "productState": 0] as [String : Any]
    
    
}
